### PR TITLE
add 1.18.2 compat

### PR DESCRIPTION
**Pull request by triphora**
The signature of the methods had to be changed as there was a new local variable, and the ordinal had to be changed from 0 to 1 for the two that used 1.

link for anyone who wants it: https://cdn.discordapp.com/attachments/745979270748307458/951967909943586866/NoFog-1.2.01.16.5-1.18.2.jar

### CODE REVIEW

**Comment by triphora** [comment]
Updated to 22w06a. Probably won't work on older versions, since I'm not sure how you want me to abstract stuff like the registry changes.

**Comment by Virtuoel** [comment]
Had a feeling something breaking was coming with vanilla, hence why I didn't merge earlier, but I didn't expect the break to be registry changes. With that sort of sweeping change to vanilla, might be best to wait until 1.18.2 is fully out before merging to make sure we don't get hit by any further big changes.

**Comment by triphora** [comment]
Right, I wasn't expecting you to merge until then, but I had made the changes for my personal 22w03a/06a world and thought I might as well PR them /shrug

**Comment by Ynng** [comment]
The fork worked on 1.18.2 for me, mod menu also works fine: https://github.com/wafflecoffee/NoFog/pull/1

**Comment by Virtuoel** [comment]
This PR does work fine. Once the weekend comes around, this will be merged and updated for 1.18.2.

**Comment by Virtuoel** [comment]
Merged in 760eb89127872ebaaa9744547aa0dfb96c9ec078

**Pull request closed without merging**
